[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
alice = "9xgoWvbQV1voGBGeqTttuUpuvwyJECeqzRFyxqY5NYpE"
day33 = "8cS25W65T8isi3WoGTX6SNdN5wZjbd8EzvjJPrTQKiFK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
